[theme]
base="dark"

gatherUsageStats = false

# screens and components. Examples of widgets using this color are st.slider and st.checkbox.
primaryColor = "#588000" 

# Background color for the container.
backgroundColor = "#333F00"
secondaryBackgroundColor =  "#799933" 


# Font color for the page.
textColor = "#F9F9FF"

# Font family (serif | sans serif | mono) for the page. Will not impact code areas.
# Default: "sans serif"
font = "monospace"

#Better not to change color values w/o discussing with PaulB