[theme]
base="dark"

gatherUsageStats = false

# screens and components. Examples of widgets using this color are st.slider and st.checkbox.
primaryColor = "chartreuse"

# Background color for the container.
backgroundColor = "#40546f" #4c6483" 
secondaryBackgroundColor =  "#738599" 


# Font color for the page.
textColor = "#F9F9FF"

# Font family (serif | sans serif | mono) for the page. Will not impact code areas.
# Default: "sans serif"
font = "monospace"

#Better not to change color values w/o discussing with PaulB